.TH EMPATHY "1" "October 2007" "Telepathy project" "User Commands"
.SH NAME
empathy \- GNOME instant messaging client using Telepathy
.SH SYNOPSIS
empathy
.SH DESCRIPTION
Empathy consists of a rich set of reusable instant messaging widgets, and a
GNOME client using those widgets.
It uses Telepathy and Nokia's Mission Control, and reuses Gossip's UI.
.PP
The main user interface consists of a contact list window and an icon in the
notification area.
.SH OPTIONS
There are no command-line options.
.SH ENVIRONMENT
.TP
\fBEMPATHY_LOGFILE\fR=\fIfilename\fR
If set, debug output will go to the given file rather than to stderr.
.TP
\fBEMPATHY_DEBUG\fR=\fItype\fR
May be set to "all" for full debug output, or various undocumented options
(which may change from release to release) to filter the output.
.SH SEE ALSO
\fIhttp://telepathy.freedesktop.org/\fR, \fIhttp://live.gnome.org/Empathy\fR
