.TH EMPATHY-ACCOUNTS "1" "October 2007" "Telepathy project" "User Commands"
.SH NAME
empathy\-accounts \- configure Telepathy instant messaging accounts
.SH SYNOPSIS
empathy\-accounts
.SH DESCRIPTION
empathy-accounts displays a graphical (Gtk+) dialog where the instant messaging
accounts used by Empathy (via Telepathy Mission Control) can be configured.
.SH OPTIONS
There are no command-line options.
.SH SEE ALSO
\fIhttp://telepathy.freedesktop.org/\fR, \fIhttp://live.gnome.org/Empathy\fR
